config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  get 'home/index'
  root to: "home#index"

  resources :items do
    resources :user_items, only: [:index, :create, :new, :index]
  end
  resources :cards, only: [:new, :create]
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :user_items
  has_one_attached :image
  belongs_to :user
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  with_options presence: true do
    validates :image
    validates :name
    validates :explanation
    validates :category_id, numericality: {other_than:1 }
    validates :price, numericality: { only_integer: true }, format: { with:/\A[0-9]+\z/ }
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @item = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to root_path
  end

  private
  def item_params
    params.require(:item).permit(:name, :explanation, :category_id, :price, :image).merge(user_id: current_user.id)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1>商品登録</h1>
<%= form_with model: @item, local: true do |f|%>
<h3>画像</h3>
<%= f.file_field :image, name: 'item[image]' %>
<h3>名前</h3>
<%= f.text_area :name %>
<h3>説明文</h3>
<%= f.text_area :explanation %>
<h3>カテゴリー</h3>
<%= f.collection_select(:category_id, Category.all, :id, :name, {}) %>
<h3>価格</h3>
<%= f.text_field :price %>
</br>
<%= f.submit "編集する" %>
<% end %>
<%= link_to "トップページ", root_path %>

app/views/items/index.html.erb
商品一覧

<% @item.each do |item| %>
<%= link_to item_path(item.id) do %>
<%= image_tag item.image.variant(resize: '300x300') %>
<%= item.name %>
<% end %>
<%= item.explanation %>
<%= item.category.name %>
<%= item.price %>
<% end %>

<%= link_to "トップページ" ,root_path %>

app/views/items/new.html.erb
<h1>商品登録</h1>
<%= form_with model: @item, local: true do |f|%>
<h3>画像</h3>
<%= f.file_field :image, name: 'item[image]' %>
<h3>名前</h3>
<%= f.text_area :name %>
<h3>説明文</h3>
<%= f.text_area :explanation %>
<h3>カテゴリー</h3>
<%= f.collection_select(:category_id, Category.all, :id, :name, {}) %>
<h3>価格</h3>
<%= f.text_field :price %>
</br>
<%= f.submit "出品する" %>
<% end %>

app/views/items/show.html.erb
<%= link_to "編集", edit_item_path %>
<%= link_to '削除', item_path(@item.id), method: :delete %>
<%= link_to '購入', item_user_items_path(@item.id) %>
<%= link_to "トップページ", root_path %>