config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  get 'home/index'
  root to: "home#index"

  resources :items do
    resources :user_items, only: [:index, :create, :new, :index]
  end
  resources :cards, only: [:new, :create]
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
  end

  def create
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"] # 環境変数を読み込む
    customer = Payjp::Customer.create(
    description: 'test', # テストカードであることを説明
    card: params[:card_token] # 登録しようとしているカード情報
    )

    card = Card.new( # トークン化されたカード情報を保存する
      card_token: params[:card_token], # カードトークン
      customer_token: customer.id, # 顧客トークン
      user_id: current_user.id # ログインしているユーザー
    )
    if card.save
      redirect_to root_path
    else
      redirect_to "new"
    end
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.erb
<%= form_with  url: cards_path, id: 'charge-form', class: 'card-form',local: true do |f| %>
<div class="Cardpage">
    <h1>カード登録</h1>
  </div><br>
  <div class='form-wrap'>
    <%= f.label :number, "【カード番号】" %>
    <%= f.text_field :number, class:"number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
  </div>
  <div class='form-wrap'>
    <%= f.label :cvc ,"【ＣＶＣ】" %>
    <%= f.text_field :cvc, class:"cvc", placeholder:"カード背面にある3桁の番号", maxlength:"4" %>
  </div>
  <div class='form-wrap'>
  <br>
    <p>【有効期限】</p>
    <div class='input-expiration-date-wrap'>
      <%= f.select :exp_month, 1..12, {include_blank: "---"}, class: "exp_month" %>
      <p>月</p>
      <%= f.select :exp_year, 20..25, {include_blank: "---"}, class: "exp_year" %>
      <p>年</p>
    </div>
  </div>
  <%= f.submit "登録する" , class:"button" %>
<% end %>